apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    env: dev
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/data"